org.gradle.jvmargs=-Xms256m -Xmx1536m -Xss512k -XX:+UseSerialGC -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=192m -XX:ActiveProcessorCount=2 -XX:CICompilerCount=2 -Dkotlin.daemon.jvm.options=-Xmx768m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.vfs.watch=false
kotlin.daemon.jvmargs=-Xmx768m
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=false
