org.gradle.jvmargs=-Xms256m -Xmx768m -XX:MaxMetaspaceSize=256m -XX:HeapBaseMinAddress=4g -Dkotlin.daemon.jvm.options=-Xmx256m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
kotlin.daemon.jvmargs=-Xmx256m
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
