// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2IPNm1Zfp7o3ivZXNRGzUqDRyknOebqY',
    appId: '1:727484357557:android:af8b733a0872356d9217fc',
    messagingSenderId: '727484357557',
    projectId: 'bock-one-cacd4',
    storageBucket: 'bock-one-cacd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0cDPnyMEPiEGBRBkKiVnzZ3cA3zEXIY',
    appId: '1:727484357557:ios:2f613802e141d0ae9217fc',
    messagingSenderId: '727484357557',
    projectId: 'bock-one-cacd4',
    storageBucket: 'bock-one-cacd4.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmCyDYnq-AeVSGXbEk10aouWbBY8Vy4mY',
    appId: '1:727484357557:web:d84ca55a43bba5ba9217fc',
    messagingSenderId: '727484357557',
    projectId: 'bock-one-cacd4',
    authDomain: 'bock-one-cacd4.firebaseapp.com',
    storageBucket: 'bock-one-cacd4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0cDPnyMEPiEGBRBkKiVnzZ3cA3zEXIY',
    appId: '1:727484357557:ios:2f613802e141d0ae9217fc',
    messagingSenderId: '727484357557',
    projectId: 'bock-one-cacd4',
    storageBucket: 'bock-one-cacd4.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmCyDYnq-AeVSGXbEk10aouWbBY8Vy4mY',
    appId: '1:727484357557:web:bcb9830ebdf51c0b9217fc',
    messagingSenderId: '727484357557',
    projectId: 'bock-one-cacd4',
    authDomain: 'bock-one-cacd4.firebaseapp.com',
    storageBucket: 'bock-one-cacd4.firebasestorage.app',
  );

}